---
- name: Ssh key
  authorized_key:
    user: "{{ username }}"
    state: present
    key: "{{ lookup('file', '/home/<user>/<pubkey>') }}"

- name: Configure sshd
  lineinfile:
    path: "/etc/ssh/sshd_config"
    regex: "^(#)?{{item.key}}"
    line: "{{item.key}} {{item.value}}"
    state: present
  loop:
    - { key: "PermitRootLogin", value: "no" }
    - { key: "PasswordAuthentication", value: "no" }
  notify:
    - Restart sshd

